AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Nginx on ECS with T3 Medium Instances and ALB

Parameters:
  VpcId:
    Type: String
    Description: ID of the existing VPC
  SubnetIds:
    Type: CommaDelimitedList
    Description: List of existing subnet IDs in the VPC

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: nginx-cluster

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: nginx-task
      Cpu: "512"
      Memory: "1GB"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: nginx-container
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      ServiceName: nginx-service
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref SubnetIds

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: nginx-load-balancer
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !GetAtt ALBSecurityGroup.GroupId
      Scheme: internet-facing
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: nginx-target-group
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic to ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  NginxServiceURL:
    Description: URL for the deployed Nginx service
    Value: !Sub "http://${LoadBalancer.DNSName}"
